import { library } from '@fortawesome/fontawesome-svg-core'

// Light
import {
  faAngleUp,
  faAngleDown,
  faBatterySlash,
  faBatteryEmpty,
  faBatteryLow,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faBatteryBolt,
  faDroplet,
  faForward,
  faGlobe,
  faHouseChimney,
  faLightbulb,
  faLocationCrosshairs,
  faPersonWalking,
  faPowerOff,
  faPause,
  faPlay,
  faRouter,
  faStop,
  faSensor,
  faSensorOn,
  faSensorTriangleExclamation,
  faTemperatureHalf,
  faTimer,
  faTriangleExclamation,
  faVolume,
  faVolumeHigh,
  faVolumeLow,
  faVolumeXmark,
  faWifi,
} from '@fortawesome/pro-solid-svg-icons'

import {
  faYoutube as fabYoutube,
  faApple as fabApple,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  // Brands
  fabApple,
  fabYoutube,
  // Solid
  faAngleUp,
  faAngleDown,
  faBatterySlash,
  faBatteryEmpty,
  faBatteryLow,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faBatteryBolt,
  faDroplet,
  faForward,
  faGlobe,
  faHouseChimney,
  faLightbulb,
  faLocationCrosshairs,
  faPersonWalking,
  faPowerOff,
  faPause,
  faPlay,
  faRouter,
  faStop,
  faSensor,
  faSensorOn,
  faSensorTriangleExclamation,
  faTemperatureHalf,
  faTimer,
  faTriangleExclamation,
  faVolume,
  faVolumeHigh,
  faVolumeLow,
  faVolumeXmark,
  faWifi
)
