import { library } from '@fortawesome/fontawesome-svg-core'

// Light
import {
  faAngleUp,
  faAngleDown,
  faBrightness,
  faDoorClosed,
  faDoorOpen,
  faDroplet,
  faFan,
  faForward,
  faGlobe,
  faHouseChimney,
  faLightbulb,
  faLocationCrosshairs,
  faPerson,
  faPersonWalking,
  faPowerOff,
  faPause,
  faPlay,
  faRouter,
  faSeedling,
  faSensor,
  faSensorOn,
  faSensorTriangleExclamation,
  faStop,
  faTemperatureHalf,
  faTimer,
  faTriangleExclamation,
  faVolume,
  faVolumeHigh,
  faVolumeLow,
  faVolumeXmark,
  faWeightHanging,
  faWifi,
  faWindowFrameOpen,
} from '@fortawesome/pro-solid-svg-icons'

import {
  faBatterySlash as farBatterySlash,
  faBatteryEmpty as farBatteryEmpty,
  faBatteryLow as farBatteryLow,
  faBatteryQuarter as farBatteryQuarter,
  faBatteryHalf as farBatteryHalf,
  faBatteryThreeQuarters as farBatteryThreeQuarters,
  faBatteryFull as farBatteryFull,
  faBatteryBolt as farBatteryBolt,
} from '@fortawesome/pro-regular-svg-icons'

import {
  faYoutube as fabYoutube,
  faApple as fabApple,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  // Brands
  fabApple,
  fabYoutube,
  // Regular
  farBatterySlash,
  farBatteryEmpty,
  farBatteryLow,
  farBatteryQuarter,
  farBatteryHalf,
  farBatteryThreeQuarters,
  farBatteryFull,
  farBatteryBolt,
  // Solid
  faAngleUp,
  faAngleDown,
  faBrightness,
  faDoorClosed,
  faDoorOpen,
  faDroplet,
  faFan,
  faForward,
  faGlobe,
  faHouseChimney,
  faLightbulb,
  faLocationCrosshairs,
  faPerson,
  faPersonWalking,
  faPowerOff,
  faPause,
  faPlay,
  faRouter,
  faSeedling,
  faStop,
  faSensor,
  faSensorOn,
  faSensorTriangleExclamation,
  faTemperatureHalf,
  faTimer,
  faTriangleExclamation,
  faVolume,
  faVolumeHigh,
  faVolumeLow,
  faVolumeXmark,
  faWeightHanging,
  faWindowFrameOpen,
  faWifi
)
